# Use postgres/example user/password credentials
version: '3.1'

services:
  db_tourplanner:
    image: postgres:15.1
    restart: always
    environment:
      POSTGRES_USER: swen-tourplanner-user
      POSTGRES_PASSWORD: tourplanner-password
      POSTGRES_DB: swen-tourplanner-db
    ports:
      - '5432:5432'
    volumes:
      - db_tourplanner:/var/lib/postgresql/data

  db_test-tourplanner:
    image: postgres:15.1
    restart: always
    environment:
      POSTGRES_USER: swen-test-user
      POSTGRES_PASSWORD: test-password
      POSTGRES_DB: swen-test-db
    ports:
      - '5431:5432'
    volumes:
      - db_tourplanner-test:/var/lib/postgresql/data

volumes:
  db_tourplanner:
    driver: local
  db_tourplanner-test:
    driver: local